### ISSUE TITLE
Error while compiling code for NODE_MCU

### ISSUE THREAD

**Issue by Mitty224** [TemiusIII/DIWHY_Led#2]
In file included from /Users/mitty/Documents/Arduino/libraries/FastLED/src/FastLED.h:75,
                 from /Users/mitty/Documents/Arduino/led_web/led_web.ino:4:
/Users/mitty/Documents/Arduino/libraries/FastLED/src/fastspi.h:157:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  157 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mitty/Documents/Arduino/led_web/led_web.ino: In function 'String get_data(String)':
/Users/mitty/Documents/Arduino/led_web/led_web.ino:159:1: error: control reaches end of non-void function [-Werror=return-type]
  159 | }
      | ^
cc1plus: some warnings being treated as errors

exit status 1

Compilation error: control reaches end of non-void function [-Werror=return-type]

**Comment by TemiusIII** [comment]
Are you using mac os?

**Comment by Mitty224** [comment]
Yes

**Comment by TemiusIII** [comment]
Try compiling on windows, it should give you only a warning

**Comment by Mitty224** [comment]
Thanks, that helped!

**Comment by TemiusIII** [comment]
I figured out why this error was appearing. To fix that you should just  download the latest ESP8266 board package. Added this to the README.MD
